### ISSUE TITLE
Let's formalize submission formats in README

### ISSUE THREAD

**Issue by mikiSpoko200** [ppolesiuk/type-systems-notes#6]
I think that some set of basic guidelines, regarding possible ways to contribute should be compiled. As of now I find it difficult to figure out how exactly do we want this repository to look like.

Issues that I think should be addressed are as follows:
- during classes a general desire was expressed by many to allow contributions in other formats than tex. In my opinion best way to handle these would be via wiki. Let's keep tex document nice and clean.
- how exactly tex documents are to be structured? Should definitions be interleaved with (ideally elaborate) explanations of said definitions or perhaps all but the most relevant details should be placed at the very bottom of the document in separate section(s) similarly to the *Further Reading*.

Regarding the last issue I think I would be nice to separate elaborate descriptions into separate files and just *inline* them in bigger document (I assume latex can do that sort of thing). It would certainly make collisions much less common and simplify the versioning as well as make it easier to select specific parts of specific submissions.

**Comment by ppolesiuk** [comment]
> I think that some set of basic guidelines, regarding possible ways to contribute should be compiled. As of now I find it difficult to figure out how exactly do we want this repository to look like.

The whole project is quite experimental, and as for now I have no clear idea how the ideal workflow could look like. At this early stage I'm open to any ideas and contributions that push the project forward, just to see which of them work well.

> during classes a general desire was expressed by many to allow contributions in other formats than tex. In my opinion best way to handle these would be via wiki.

I totally agree. I will setup some wiki in the near future (probably this evening).

> Let's keep tex document nice and clean.

From my experience, working on tex document is different than working on code. While managing tex macros and keeping them consistent throughout the project have some similarities with the code development, writing a prose is different. It is good to have something written, even if it's far from the ideal, and then constantly improve it. Therefore, at least at the beginning, I can accept changes in the tex document that are not clean enough. Of course, at some point making another improvements will require some discussion, and wiki may turn out to be helpful, but I think it is rather far future.

> how exactly tex documents are to be structured? Should definitions be interleaved with (ideally elaborate) explanations of said definitions or perhaps all but the most relevant details should be placed at the very bottom of the document in separate section(s) similarly to the Further Reading.

My initial idea was to have elaborate book-like explanations interleaved with math (like in proper math textbooks). If some topic would require more elaboration that do not fit to the main narration, we can make separate section/chapter for it.

> Regarding the last issue I think I would be nice to separate elaborate descriptions into separate files and just inline them in bigger document (I assume latex can do that sort of thing). It would certainly make collisions much less common and simplify the versioning as well as make it easier to select specific parts of specific submissions.

For this reason I put each chapter in a separate file, and after each lecture I create a new chapter with a structure of sections that follow the lecture. For writing a prose, I suggest to work on one section at time and put all section-related macros at the beginning of the section in order to avoid collisions.

**Comment by ppolesiuk** [comment]
I've created a page on wiki that describes some guideline for contribution. I've also updated README to point to this guideline. If someone has more ideas how we can organize workflow, I invite to create a separate discussion (in Github's discussions).
